title: 'Simple OSRS OSAAT Progress Tracker'
description: 'Simple progress tracker for the OSRS XOSAAT gamemode'
baseurl: '/osrs-progress' 
url: 'https://sequenter.github.io'
github_username: 'sequenter'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - README.md